# Generated by Django 5.1.1 on 2024-10-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
