# Generated by Django 5.1.1 on 2024-10-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_subject_sunjectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SunjectMarks',
            new_name='SubjectMarks',
        ),
    ]
